config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to:"static_pages#index"

  get 'sobre', to: 'static_pages#sobre'

  get 'contato', to: 'static_pages#contato'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    @nome = "Jovennan"
  end

  def sobre
  end

  def contato
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
<small>
  <%= link_to 'Contact List. Todos os direitos reservados', root_path %>
</small>

<nav>
  <ul>
    <li>
      <%= link_to 'Sobre', sobre_path %>
    </li>
    <li>
      <%= link_to 'Contato', contato_path %>
    </li>
  </ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#expanded-menu" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Contact List', root_url, class: 'navbar-brand'%>
    </div>

    <!-- Conteudo exibido em telas maiores e que serão escondidos em telas menores -->
    <div class="collapse navbar-collapse" id="expanded-menu">
      <ul class="nav navbar-nav">
        <li class="active">
          <a href="#">Nova Conta</a>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to 'Entrar', '#'%>
        </li>
      </ul>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer'%>
    </div>

  </body>
</html>

app/views/static_pages/contato.html.erb
<h1>Contato</h1>

<p>
  Entre em contato com <a href="http://www.twitter.com/jovennan"></a> para saber mais.
</p>

app/views/static_pages/index.html.erb
<div class="jumbotron">
  <h1>Contact List</h1>
  <p>
    Gerencie seus contatos em qualquer lugar!
  </p>
  <p>
    <%= link_to 'Crie Sua Conta', '#', class: 'btn btn-primary btn-lg' %>
  </p>
</div>

app/views/static_pages/sobre.html.erb
<h1>Sobre</h1>

<p>
  Criado com o intúito de aprender um pouco sobre o framework Ruby on Rails, Contact List uma feramenta poderosa. 
</p>